/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const set_server_url: (a: number, b: number) => void;
export const render_document: (a: any, b: any, c: number, d: number) => [number, number, number];
export const __wbg_shtmlmounthandle_free: (a: number, b: number) => void;
export const shtmlmounthandle_unmount: (a: number) => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_export_5: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h79b8674778044267: (a: number, b: number) => void;
export const closure43_externref_shim: (a: number, b: number, c: any) => void;
export const closure81_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const closure202_externref_shim: (a: number, b: number, c: any) => number;
export const __wbindgen_start: () => void;
