import Head from "next/head";
import { getMMTCustomId, MMT_CUSTOM_ID_PREFIX } from "@stex-react/utils";

export function MyCompo() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{getMMTCustomId('ooooo')}</div>
    </>
  );
}
